svenevs/exhale

docs/reference_exhale_configs.rst
exhale/configs.py
exhale/deploy.py
exhale/utils.py

Fixes #14.
- colorized printing is really ugly in the online build logs
- capturing doxygen output can cause builds to fail for medium sized projects, the subprocess buffer overflows and the build will silently fail after `cat conf.py`

remove color printing and doxygen output on RTD

---

.appveyor.yml
docs/conf.py
docs/mastering_doxygen.rst
exhale/parse.py

Fix doxygen ci differently (again [again [again]])

---

.appveyor.yml
.travis.yml
docs/conf.py
exhale/__init__.py
testing/conftest.py
tox.ini

Breathe 4.13 requires Sphinx 2.0 or later.  Planned patch releases of exhale will be able to support older versions of Sphinx still, but the testing / CI setup needs to change slightly.

repair testing suite to still test with py2.7

---

README.rst
docs/_static/custom.css
docs/changelog.rst
docs/conf.py
docs/index.rst
docs/reference/configs.rst
exhale/configs.py
exhale/deploy.py
exhale/graph.py
exhale/parse.py
exhale/utils.py
testing/base.py
testing/conftest.py
testing/tests/configs.py
testing/tests/cpp_pimpl.py

Fixes #64.
- Default to trimming `dir` and `file`.
- Utilize `:orphan:` page attribute (to be continued?).

Allow unabridged API to exclude different kinds.

---

requirements.txt

From PyPI's description for `bs4`:
> This package ensures that if you type pip install bs4 by mistake you
> will end up with Beautiful Soup.
Using the proper package makes packaging exhale a little simpler.

Use the proper beautifulsoup package

---

.github/workflows/test_python.yaml
docs/testing.rst
docs/testing/projects.rst
docs/testproject.py
setup.cfg
testing/base.py
testing/hierarchies.py
testing/projects/__init__.py
testing/projects/c_maths/__init__.py
testing/projects/cpp with spaces/__init__.py
testing/projects/cpp_fortran_mixed/__init__.py
testing/projects/cpp_func_overloads/__init__.py
testing/projects/cpp_long_names/__init__.py
testing/projects/cpp_nesting/__init__.py
testing/projects/cpp_pimpl/__init__.py
testing/tests/c_maths.py
testing/tests/configs_tree_view.py
testing/tests/cpp_fortran_mixed.py
testing/tests/cpp_func_overloads.py
testing/tests/cpp_long_names.py
testing/tests/cpp_nesting.py
testing/tests/cpp_pimpl.py
testing/tests/cpp_with_spaces.py
tox.ini

- each testing/projects/{project} is dynamically imported
- provides definitions for expected class / file hierarchies
- hierarchies are deep copied, tests that reuse previously
mutated these
- docs updated to use automodule, except `cpp with spaces`
(not possible to document in sphinx)
- ignore `from collections import MutableMapping` warnings
(see also #119)
- skip mac builds on CI until #122 is solved
- install correct beautiful soup package in tox.ini
- fix url parsing in docs/testproject.py
These should never have been cluttered into #114...

restructure testing framework

---

docs/changelog.rst
exhale/__init__.py
setup.py

Before (just building the `exhale-companion` with `pip install sphinx` then `pip install exhale` (order mattered again, because of #120 I think, vanilla `pip install exhale` fails :cry:):
```console
$ sphinx-build -j 4 -b html -vv . _build &> output.txt
$ python -c 'import exhale; print(exhale.__version__)'
0.2.3
$ grep WARNING output.txt | grep -i parallel
WARNING: the exhale extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```
Now doing `pip install -e [this branch]`
```console
$  sphinx-build -j 4 -b html -vv . _build &> output.txt
$  python -c 'import exhale; print(exhale.__version__)'
0.2.4.dev
$ grep WARNING output.txt | grep -i parallel
```

enable parallel builds with sphinx

---

README.rst
docs/changelog.rst
docs/reference/configs.rst
exhale/configs.py
exhale/deploy.py
exhale/graph.py
exhale/utils.py
testing/base.py
testing/projects/cpp_nesting/include/page_town_rock.hpp
testing/projects/cpp_nesting/include/page_town_rock_alt.hpp
testing/tests/configs_tree_view.py
testing/tests/cpp_nesting.py

Closes #111. This patch is a first stab at supporting Doxygen pages. Namely, it:
- Includes Doxygen's main page in the root file
- Allows page listings in the unabridged API
- Displays a page hierarchy (ignoring the main page)
- Makes the root title optional to avoid duplicates
This is lacking tests (and some existing tests are failing on `master`), but I'd like to get some preliminary feedback.

Add support for Doxygen pages

---

docs/changelog.rst
exhale/graph.py

Precisely what the title says. Some template partial specializations may contain `*` that if not escaped are confused by `docutils` as *emphasis* syntax.

Escape '*' in template page titles.

---

exhale/graph.py

The target node for a link can be missing e.g. when it is explicitly
excluded from the Doxygen documentation and thus doesn't appear
in the XML output. This is a quick workaround that skips the link
generation instead of aborting.
This also works around #63.

Skip link generation when target node is missing

---

tox.ini

Fixes #131.
~~4.7.0 not on PyPI yet, they're currently preparing the release.  Will re-run this after they do.~~

pin lxml>=4.6.4 for windows dev convenience

---

docs/testproject.py

When cloning a GitHub repository with ssh, the URL may be either:
git@github.com:user/repo
or:
git@github.com:user/repo.git
This PR makes it so either is allowed.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Fix the parsing of the git remote.

---

docs/changelog.rst
docs/reference/configs.rst
exhale/graph.py
testing/base.py
testing/tests/configs_tree_view.py
testing/tests/cpp_pimpl.py

Sphinx does not like it when a file that is later included
(via .. include directive) has the very same link label inside of
it.  To avoid a Sphinx warning, skip link label generation for
the pageindex.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

avoid duplicate label warnings for .. include::'ed files 

---

docs/changelog.rst
exhale/utils.py
testing/tests/cpp_nesting.py

Take advantage of the utils.specificationsForKind returning any possible default or customSpecificationsForKind by user being used to manufacture every directive to also stuff in
:project: {app.config.breathe_default_project}
Refs: #27
@florianhumblot I did some local testing and this doesn't appear to break the status quo for exhale's (unfortunate) single-project-only builds.  Are you able to test this and see if it works for you with multiproject and the monkeypatch?  It's definitely a hack but well, I'm OK with using a hack to support a hack :upside_down_face:  As noted in the comment in the diff, multiproject support "properly" effectively requires a rewrite of this whole darn thing.  One day...
pip install git+https://github.com/svenevs/exhale.git@fix/multiproj-monkeypatch
That will …

revive support for the multiproject monkeypatch

---

docs/changelog.rst
exhale/graph.py

This reverts commit 0d1a8a832e7c2efe1f7766d501bd23a96f6f9f8a.
With this in place, I was getting errors of the kind:
```
docs_build/rcl_lifecycle/rcl_lifecycle/default_sphinx_project/generated/index.rst:3: CRITICAL: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'default_sphinx_project/generated/page_view_hierarchy.rst.include'.
```
That is, because `final_data_string` is empty, we were never creating `page_view_hiearchy.rst.include`, but we were still trying to `.. include` it.  Revert this patch, which seems to make things happier.  @roehling FYI.  @svenevs What do you think?

Check if the hierarchy files exist before generating includes.

---

docs/changelog.rst
exhale/utils.py

Prevents multiple `:project:` tags from being added to a breathe directive.
Fixes the issue that PR #146 tries to prevent.

Prevent multiple project specification

---

docs/changelog.rst
exhale/utils.py

This PR fixes a bug in `exhale/utils.py:specificationsForKind(kind)`. When using a custom directive function with `customSpecificationsMapping`, the specifications for the kinds `struct` and `class` were overwritten.

fix customSpecificationsMapping for kind 'class' and 'struct'

---

docs/todo.rst
tox.ini

- use older Jinja2 until sphinx 3.x is dropped
https://github.com/sphinx-doc/sphinx/issues/10291
- linkcheck: roadmap was deleted

fix ci again

---

tox.ini

This is no longer necessary and wastes developer time.

Stop installing breathe from git for testing

---

pyproject.toml

Prevents build output from being littered with e.g.,
coverage/report.py:87:
CoverageWarning: Couldn't parse
'exhale/testing/projects/cpp_nesting/docs_TreeViewHierarchyTests_test_common/conf.py': No source for code:
'exhale/testing/projects/cpp_nesting/docs_TreeViewHierarchyTests_test_common/conf.py'. (couldnt-parse)
coverage._warn(msg, slug="couldnt-parse")

Exclude generated conf.py from code coverage

---

docs/changelog.rst
exhale/data/treeView-bootstrap/bootstrap-treeview/apply-bootstrap-treview.js
exhale/graph.py

The introduction of the page hierarchies broke the bootstrap tree for any project that does not use `page`.  Solution is to only select / apply the `treeview` functions if the id anchors are found.

Fix sphinx-bootstrap-theme styling

---

docs/changelog.rst
exhale/graph.py
testing/hierarchies.py

Fixes #171.
Some pages do not have any additional information between the
parent backlink and the title heading.  In this event there is no
newline between the comment and the heading markup resulting in
warnings from sphinx.

Guarantee a newline always follows |exhale_lsh| backlinks

---

.github/workflows/test_extras.yaml
.github/workflows/testing_projects.yaml

`fai-fast` just works with `matrix`.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

Fix GH Actions fail-fast usage
